name: chess_app
description: A cross-platform multiplayer chess application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  chess: ^0.8.1
  # --- State Management ---
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5       # Helps compare Game States
  get_it: ^7.6.4          # Dependency Injection

  # --- UI & Assets ---
  flutter_svg: ^2.0.9     # For rendering Chess Pieces (.svg)
  google_fonts: ^6.1.0    # Nice typography
  font_awesome_flutter: ^10.6.0

  # --- Navigation ---
  go_router: ^13.0.0      # Deep linking (for invite links)

  # --- Logic ---
  uuid: ^4.2.1            # Generating Game IDs
  # chess: ^0.8.1         # (Optional) Use this later for move validation logic

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bloc_test: ^9.1.5
  mocktail: ^1.0.0

flutter:
  uses-material-design: true

  # Enable assets for your pieces
  assets:
    - assets/pieces/
    #- assets/sounds/